"""test

Revision ID: 482a5825bffa
Revises: 8bd6012c8e5f
Create Date: 2026-09-11 02:05:05.281318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '482a5825bffa'
down_revision: Union[str, Sequence[str], None] = '8bd6012c8e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_comments_user_id_users', 'comments', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_tasks_project_id_projects', 'tasks', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_project_id_projects', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_comments_user_id_users', 'comments', type_='foreignkey')
    # ### end Alembic commands ###
